---
- name: Install and Configure Pi-hole with Unbound
  hosts: pihole_clients_server
  become: yes
  vars:
    pihole_password: "kashmir02"  # Change to your desired password
    dns_interface: "eth1"  # Interface for DNS resolution
    web_interface: "eth2"  # Interface for Pi-hole Web UI
    upstream_dns: "127.0.0.1#5335"

  tasks:

    - name: Update package cache and install dependencies
      apt:
        update_cache: yes
        name:
          - curl
          - git
          - apt-transport-https
          - ca-certificates
          - unbound
        state: present

    - name: Download and install Pi-hole
      shell: curl -sSL https://install.pi-hole.net | bash
      args:
        creates: /etc/pihole/setupVars.conf
      register: pihole_install
      changed_when: "'Pi-hole blocking is enabled' in pihole_install.stdout"

    - name: Configure Pi-hole settings
      template:
        src: setupVars.j2
        dest: /etc/pihole/setupVars.conf
      notify: Restart Pi-hole

    - name: Configure Unbound for Recursive DNS Resolving
      copy:
        dest: /etc/unbound/unbound.conf.d/pi-hole.conf
        content: |
          server:
            verbosity: 1
            interface: 127.0.0.1
            port: 5335
            do-ip4: yes
            do-udp: yes
            do-tcp: yes
            root-hints: "/var/lib/unbound/root.hints"
            harden-glue: yes
            harden-dnssec-stripped: yes
            use-caps-for-id: no
            edns-buffer-size: 1232
            cache-min-ttl: 3600
            cache-max-ttl: 86400
            prefetch: yes
            num-threads: 4
            so-rcvbuf: 1m
            so-sndbuf: 1m
      notify: Restart Unbound

    - name: Download Root Hints for Unbound
      get_url:
        url: https://www.internic.net/domain/named.cache
        dest: /var/lib/unbound/root.hints
        mode: '0644'
      notify: Restart Unbound

    - name: Ensure Pi-hole uses Unbound as upstream DNS
      lineinfile:
        path: /etc/pihole/setupVars.conf
        regexp: '^PIHOLE_DNS_1='
        line: "PIHOLE_DNS_1={{ upstream_dns }}"
      notify: Restart Pi-hole

    - name: Set Pi-hole DNS server to listen on eth1
      lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        regexp: '^interface='
        line: "interface={{ dns_interface }}"
      notify: Restart Pi-hole

    - name: Configure Lighttpd to listen on eth2 for web interface
      copy:
        dest: /etc/lighttpd/external.conf
        content: |
          server.bind = "{{ web_interface }}"
      notify: Restart Lighttpd

    - name: Set Admin Password for Pi-hole
      shell: pihole -a -p "{{ pihole_password }}"

  handlers:
    - name: Restart Pi-hole
      command: pihole restartdns

    - name: Restart Unbound
      systemd:
        name: unbound
        state: restarted

    - name: Restart Lighttpd
      systemd:
        name: lighttpd
        state: restarted
