---
- name: Install pve_server
  hosts: pve_server
  become: yes

  tasks:
    
    - name: Disable subscription nag in Web UI
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        # Zoek de code die de nag toont en forceer dat deze nooit true wordt
        regexp: 'if \(data\.status === "Active"\)'
        replace: 'if (false) /* disabled subscription nag */'
        backup: yes

    - name: Update en upgrade alle pakketten
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - proxmox-auto-install-assistant
          - xorriso
          - transmission-cli
          - htop
          - iotop
          - strace
          - lsof
          - mc
          - auditd
          - apparmor-utils
          - apparmor-profiles
          - git
          - neofetch
        state: present
        update_cache: yes

    - name: Preseed grub EFI reinstall
      debconf:
        name: grub-efi-amd64
        question: grub2/force_efi_extra_removable
        value: "true"
        vtype: boolean

    - name: Reinstall grub-efi-amd64
      become: yes
      shell: |
        DEBIAN_FRONTEND=noninteractive \
        apt-get install --reinstall -y grub-efi-amd64

    - name: Set up bash aliases for users
      blockinfile:
        path: "{{ item.path }}"
        create: yes
        block: |-
          alias c='clear'
          alias h='history'
          alias ls='ls -alh --color=auto'
          alias df='df -h'
          alias ports='ss -tulpn'
      loop:
        - { path: /root/.bashrc }
        - { path: /home/michael/.bashrc, owner: michael, group: michael }
      loop_control:
        label: "{{ item.path }}"

    - name: Add performance sysctl settings
      blockinfile:
        path: /etc/sysctl.d/99-performance.conf
        create: yes
        block: |-
          # Network optimizations
          net.core.rmem_max=16777216
          net.core.wmem_max=16777216
          net.ipv4.tcp_rmem=4096 87380 16777216
          net.ipv4.tcp_wmem=4096 65536 16777216
          net.core.default_qdisc=fq
          net.ipv4.tcp_congestion_control=bbr
      notify: Reload sysctl



    - name: Restart Proxmox services
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - pvedaemon
        - pveproxy
        - pvestatd

    - name: Deploy IOMMU dump script
      copy:
        dest: /usr/local/bin/iommu.sh
        mode: '0755'
        owner: root
        group: root
        content: |
          #!/bin/bash
          shopt -s nullglob
          for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
              echo "IOMMU Group ${g##*/}:"
              for d in "$g"/devices/*; do
                  echo -e "\t$(lspci -nns "${d##*/}")"
              done
          done
  handlers:

    - name: update apt cache
      apt:
        update_cache: yes

    - name: Reload sysctl
      command: sysctl --system

    - name: Restart networking
      service:
        name: networking
        state: restarted
