- name: Install Proxmox Backup Server (PBS) Community Edition
  hosts: backup_server
  become: yes

  vars:
    pbs_repo: "deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription"

  tasks:

    - name: Disable Proxmox Backup Server enterprise repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pbs-enterprise.list
        state: absent

    - name:
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
          - btrfs-progs
          - htop
          - iotop
          - mc
          - nfs-kernel-server
        state: present
        update_cache: yes

    - name: Add Proxmox Backup Server repository key
      ansible.builtin.apt_key:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        state: present

    - name: Add Proxmox Backup Server no-subscription repository
      ansible.builtin.apt_repository:
        repo: "{{ pbs_repo }}"
        state: present
        filename: proxmox-backup-server

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Proxmox Backup Server package
      apt:
        name: proxmox-backup-server
        state: present

    - name: Ensure PBS services are started and enabled
      ansible.builtin.systemd:
        name: proxmox-backup
        enabled: yes
        state: started

    - name: Comment out enterprise repo lines in pbs-enterprise.list
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/pbs-enterprise.list
        regexp: '^deb '
        replace: '# deb '
