- name: Upgrade all Fedora servers
  hosts: fedora_servers
  become: true  # Run as root

  tasks:
    - name: Update DNF package metadata
      ansible.builtin.dnf:
        update_cache: yes

    - name: Upgrade all packages using dnf
      ansible.builtin.command: dnf -y upgrade

    - name: Remove unnecessary packages
      ansible.builtin.dnf:
        autoremove: yes

    - name: Check if a reboot is required (Fedora-style)
      ansible.builtin.shell: needs-restarting -r; echo $?
      register: reboot_check
      changed_when: false

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting due to package updates."
      when: reboot_check.stdout != "0"