- name: Upgrade all Debian servers
  hosts: servers
  become: true  # Run as root

  tasks:
    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting due to package updates."
      when: reboot_required.stat.exists | default(false)
