- name: Upgrade all Debian servers
  hosts: servers
  become: true  # Run with sudo privileges
  tasks:

    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if a reboot is required
      register: reboot_required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists